[tool.bumpversion]
current_version = "1.3.3"
tag = true
tag_name = "v{new_version}"
commit = true

[[tool.bumpversion.files]]
filename = ".bumpversion.toml"

[[tool.bumpversion.files]]
filename = "README.md"
